### ISSUE TITLE
Gripper Component

### ISSUE THREAD

**Issue by LucienMorey** [thedropbears/pychargedup#28]
# Hardware

- Double-acting solenoid on the rotary cylinder to clamp the game piece

# Methods

- close - actuate the solenoid
- open - actuate the solenoid

# Sensing

I think we will need to have a sensor here to aid in our automation. What do you guys think? 

In this case, it will be helpful to identify if there is a cone within reach. This will be good for transitioning in our higher-level state machines, so we pick up a cone as soon as possible. I think that detecting the colour of an object and the distance to it from some point on the end effector will be important for this. What kind of sensors should we start playing with? I think I would start with the rev colour sensor at the very least since it can do colour and detect distance.

**Comment by DensityInfinite** [comment]
The colour detected by the sensor seems to change as the distance changes. Should we try another sensor (e.g. an distance sensor paired with a camera) for our use case?

**Comment by OliverW10** [comment]
A distance sensor would be appropriate, i believe the rev colour sensor also has a proximity sensor but I don't know what the range on that looks like.

Following our discussion today the gripper component should have the close and open methods as above but also:
- a game_piece_in_reach method which will report if the sensor can see a piece within our reach
- a has_game_piece method which will return if we have a game piece and our gripper has been closed for some amount of time (because the gripper takes a little while to actuate)
